const Map<String, String> enStrings = {
  'appTitle': 'Slangify',
  'navTranslate': 'Idiomatic Translate',
  'navSlang': 'Common Slang',
  'uiLang': 'Language',
  'inputHint': 'Enter text to translate...',
  'sourceLang': 'Source Language',
  'targetLang': 'Target Language',
  'style': 'Style',
  'degree': 'Intensity',
  'tone': 'Tone',
  'degreeLow': 'Low',
  'degreeMedium': 'Medium',
  'degreeHigh': 'High',
  'toneHappy': 'Happy',
  'toneNeutral': 'Neutral',
  'toneSad': 'Sad',
  'toneAngry': 'Angry',
  'translate': 'Translate',
  'copy': 'Copy',
  'copied': 'Copied to clipboard',
  'slangTitle': 'Common Slang',
  'filterLang': 'Language',
  'filterStyle': 'Dialect',
  'loading': 'Loading...',
  'empty': 'No results',
  'prev': 'Prev',
  'next': 'Next',
  'page': 'Page',
  'error': 'Backend connection failed',
};
