const Map<String, String> zhStrings = {
  'appTitle': 'Slangify 有内味儿',
  'navTranslate': '地道翻译',
  'navSlang': '常用俚语',
  'uiLang': '语言',
  'inputHint': '输入想要翻译的话...',
  'sourceLang': '原文语言',
  'targetLang': '目标语言',
  'style': '口语流派',
  'degree': '程度',
  'tone': '语气',
  'degreeLow': '低',
  'degreeMedium': '中',
  'degreeHigh': '高',
  'toneHappy': '开心',
  'toneNeutral': '平淡',
  'toneSad': '伤心',
  'toneAngry': '愤怒',
  'translate': '立即地道转换',
  'copy': '复制',
  'copied': '已复制到剪贴板',
  'slangTitle': '常用俚语',
  'filterLang': '语言',
  'filterStyle': '风格',
  'loading': '加载中...',
  'empty': '暂无结果',
  'prev': '上一页',
  'next': '下一页',
  'page': '页',
  'error': '连接后端失败',
};
