const Map<String, String> zhStrings = {
  'appTitle': 'SpeakNative 有内味儿',
  'introText': 'SpeakNative 是一款把翻译变成会说的应用。你不只是换语言，而是把语气、口吻、地域风格一起带过去：从标准语到方言口音、从平淡到开心/愤怒，都能一键切换。再加上每日俚语卡片式学习，让你每天都能收获一条真正活的表达。',
  'navTranslate': '地道翻译',
  'navSlang': '每日俚语',
  'uiLang': '语言',
  'inputHint': '输入想要翻译的话...',
  'sourceLang': '原文语言',
  'targetLang': '目标语言',
  'analysisToggle': '语句解析',
  'analysisTitle': '解析',
  'style': '口语流派',
  'customStyle': '自定义流派',
  'degree': '程度',
  'tone': '语气',
  'degreeLow': '低',
  'degreeMedium': '中',
  'degreeHigh': '高',
  'toneHappy': '开心',
  'toneNeutral': '平淡',
  'toneSad': '伤心',
  'toneAngry': '愤怒',
  'translate': '立即地道转换',
  'copy': '复制',
  'copied': '已复制到剪贴板',
  'slangTitle': '每日俚语',
  'filterLang': '语言',
  'filterStyle': '风格',
  'loading': '加载中...',
  'empty': '暂无结果',
  'prev': '上一页',
  'next': '下一页',
  'page': '页',
  'error': '连接后端失败',
};
